# Generated by Django 5.2.1 on 2025-06-13 13:33

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('name_uk', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Опис')),
                ('description_uk', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Опис')),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Опис')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('image', models.ImageField(blank=True, upload_to='project_categories/', verbose_name='Зображення')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категорія проєктів',
                'verbose_name_plural': 'Категорії проєктів',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('title_uk', models.CharField(max_length=200, null=True, verbose_name='Назва')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Назва')),
                ('short_description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Короткий опис')),
                ('short_description_uk', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Короткий опис')),
                ('short_description_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Короткий опис')),
                ('detailed_description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Детальний опис')),
                ('detailed_description_uk', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Детальний опис')),
                ('detailed_description_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Детальний опис')),
                ('challenge', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Завдання')),
                ('challenge_uk', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Завдання')),
                ('challenge_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Завдання')),
                ('solution', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Рішення')),
                ('solution_uk', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Рішення')),
                ('solution_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Рішення')),
                ('result', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Результат')),
                ('result_uk', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Результат')),
                ('result_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Результат')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='Клієнт')),
                ('project_date', models.DateField(verbose_name='Дата проєкту')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кількість виробів')),
                ('materials_used', models.CharField(blank=True, max_length=500, verbose_name='Використані матеріали')),
                ('main_image', models.ImageField(upload_to='projects/', verbose_name='Головне зображення')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Мета-заголовок')),
                ('meta_description', models.TextField(blank=True, verbose_name='Мета-опис')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендований')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.projectcategory', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Проєкт',
                'verbose_name_plural': 'Проєкти',
                'ordering': ['-project_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/', verbose_name='Зображення')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Підпис')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project', verbose_name='Проєкт')),
            ],
            options={
                'verbose_name': 'Зображення проєкту',
                'verbose_name_plural': 'Зображення проєктів',
                'ordering': ['order'],
            },
        ),
    ]
