# Generated by Django 5.2 on 2025-06-11 13:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='challenge_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Завдання'),
        ),
        migrations.AddField(
            model_name='project',
            name='challenge_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Завдання'),
        ),
        migrations.AddField(
            model_name='project',
            name='detailed_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Детальний опис'),
        ),
        migrations.AddField(
            model_name='project',
            name='detailed_description_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Детальний опис'),
        ),
        migrations.AddField(
            model_name='project',
            name='result_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Результат'),
        ),
        migrations.AddField(
            model_name='project',
            name='result_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Результат'),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Короткий опис'),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Короткий опис'),
        ),
        migrations.AddField(
            model_name='project',
            name='solution_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Рішення'),
        ),
        migrations.AddField(
            model_name='project',
            name='solution_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Рішення'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='description_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='name_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Короткий опис'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Опис'),
        ),
    ]
