# Generated by Django 5.2.1 on 2025-06-13 13:33

import ckeditor_uploader.fields
import django.db.models.deletion
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('name_uk', models.CharField(max_length=200, null=True, verbose_name='Назва')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Назва')),
                ('short_description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Короткий опис')),
                ('short_description_uk', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Короткий опис')),
                ('short_description_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Короткий опис')),
                ('detailed_description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Детальний опис')),
                ('detailed_description_uk', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Детальний опис')),
                ('detailed_description_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Детальний опис')),
                ('benefits', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Переваги')),
                ('benefits_uk', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Переваги')),
                ('benefits_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Переваги')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('icon', models.ImageField(blank=True, upload_to='services/icons/', verbose_name='Іконка')),
                ('main_image', models.ImageField(upload_to='services/', verbose_name='Головне зображення')),
                ('min_order_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Мін. партія')),
                ('production_time', models.CharField(blank=True, max_length=100, verbose_name='Термін виробництва')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендована')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
                'ordering': ['order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва')),
                ('title_uk', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Опис')),
                ('description_uk', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Опис')),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Опис')),
                ('icon', models.CharField(blank=True, help_text='CSS клас для іконки', max_length=50, verbose_name='Іконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.service', verbose_name='Послуга')),
            ],
            options={
                'verbose_name': 'Особливість послуги',
                'verbose_name_plural': 'Особливості послуг',
                'ordering': ['order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
    ]
