# Generated by Django 5.2 on 2025-05-30 07:36

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicefeature',
            options={'ordering': ['order'], 'verbose_name': 'Особливість послуги', 'verbose_name_plural': 'Особливості послуг'},
        ),
        migrations.AlterModelOptions(
            name='servicefeaturetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Особливість послуги Translation'},
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, upload_to='services/icons/', verbose_name='Іконка'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Рекомендована'),
        ),
        migrations.AlterField(
            model_name='service',
            name='main_image',
            field=models.ImageField(upload_to='services/', verbose_name='Головне зображення'),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='icon',
            field=models.CharField(blank=True, help_text='CSS клас для іконки', max_length=50, verbose_name='Іконка'),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.service', verbose_name='Послуга'),
        ),
        migrations.AlterField(
            model_name='servicefeaturetranslation',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='servicefeaturetranslation',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='servicetranslation',
            name='detailed_description',
            field=ckeditor.fields.RichTextField(verbose_name='Детальний опис'),
        ),
        migrations.AlterField(
            model_name='servicetranslation',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='servicetranslation',
            name='short_description',
            field=models.TextField(verbose_name='Короткий опис'),
        ),
    ]
