# Generated by Django 5.2 on 2025-06-11 13:59

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='benefits_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Переваги'),
        ),
        migrations.AddField(
            model_name='service',
            name='benefits_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Переваги'),
        ),
        migrations.AddField(
            model_name='service',
            name='detailed_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Детальний опис'),
        ),
        migrations.AddField(
            model_name='service',
            name='detailed_description_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Детальний опис'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Короткий опис'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Короткий опис'),
        ),
        migrations.AddField(
            model_name='servicefeature',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='servicefeature',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='servicefeature',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='servicefeature',
            name='title_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Короткий опис'),
        ),
    ]
