# Generated by Django 5.2 on 2025-06-11 14:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_benefits_en_service_benefits_uk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefeature',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='description_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Опис'),
        ),
    ]
