# Generated by Django 5.2 on 2025-06-11 13:24

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Історія компанії')),
                ('history_text_uk', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Історія компанії')),
                ('history_text_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Історія компанії')),
                ('mission_text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Місія')),
                ('mission_text_uk', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Місія')),
                ('mission_text_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Місія')),
                ('values_text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Цінності')),
                ('values_text_uk', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Цінності')),
                ('values_text_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Цінності')),
                ('social_responsibility', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Соціальна відповідальність')),
                ('social_responsibility_uk', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Соціальна відповідальність')),
                ('social_responsibility_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Соціальна відповідальність')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': "Сторінка 'Про нас'",
                'verbose_name_plural': "Сторінка 'Про нас'",
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('title_uk', models.CharField(max_length=200, null=True, verbose_name='Назва')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('description_uk', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('image', models.ImageField(upload_to='certificates/', verbose_name='Зображення')),
                ('issued_date', models.DateField(verbose_name='Дата видачі')),
                ('issuing_organization', models.CharField(blank=True, max_length=200, verbose_name='Організація')),
                ('certificate_url', models.URLField(blank=True, verbose_name='Посилання')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Сертифікат',
                'verbose_name_plural': 'Сертифікати',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Короткий опис компанії')),
                ('company_description_uk', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Короткий опис компанії')),
                ('company_description_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Короткий опис компанії')),
                ('mission_text', models.TextField(blank=True, verbose_name='Місія')),
                ('mission_text_uk', models.TextField(blank=True, null=True, verbose_name='Місія')),
                ('mission_text_en', models.TextField(blank=True, null=True, verbose_name='Місія')),
                ('values_text', models.TextField(blank=True, verbose_name='Цінності')),
                ('values_text_uk', models.TextField(blank=True, null=True, verbose_name='Цінності')),
                ('values_text_en', models.TextField(blank=True, null=True, verbose_name='Цінності')),
                ('hero_video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('years_experience', models.PositiveIntegerField(default=0, verbose_name='Років досвіду')),
                ('employees_count', models.PositiveIntegerField(default=0, verbose_name='Кількість співробітників')),
                ('projects_completed', models.PositiveIntegerField(default=0, verbose_name='Виконано проєктів')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Головна сторінка',
                'verbose_name_plural': 'Головна сторінка',
            },
        ),
        migrations.CreateModel(
            name='ProductionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва')),
                ('title_uk', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('description_uk', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('image', models.ImageField(upload_to='production/', verbose_name='Зображення')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендоване')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Фото виробництва',
                'verbose_name_plural': 'Фото виробництва',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('name_uk', models.CharField(max_length=100, null=True, verbose_name="Ім'я")),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name="Ім'я")),
                ('position', models.CharField(max_length=100, verbose_name='Посада')),
                ('position_uk', models.CharField(max_length=100, null=True, verbose_name='Посада')),
                ('position_en', models.CharField(max_length=100, null=True, verbose_name='Посада')),
                ('bio', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Біографія')),
                ('bio_uk', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Біографія')),
                ('bio_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Біографія')),
                ('photo', models.ImageField(upload_to='team/', verbose_name='Фото')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Електронна пошта')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_management', models.BooleanField(default=False, verbose_name='Керівництво')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Член команди',
                'verbose_name_plural': 'Команда',
                'ordering': ['order'],
            },
        ),
    ]
