# Generated by Django 5.2 on 2025-05-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_url',
            field=models.URLField(blank=True, verbose_name='Посилання'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(upload_to='certificates/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issued_date',
            field=models.DateField(verbose_name='Дата видачі'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issuing_organization',
            field=models.CharField(blank=True, max_length=200, verbose_name='Організація'),
        ),
        migrations.AlterField(
            model_name='certificatetranslation',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='certificatetranslation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='productionphoto',
            name='image',
            field=models.ImageField(upload_to='production/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='productionphoto',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='productionphoto',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Рекомендоване'),
        ),
        migrations.AlterField(
            model_name='productionphoto',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='productionphototranslation',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='productionphototranslation',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Електронна пошта'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(upload_to='team/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='teammembertranslation',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Біографія'),
        ),
        migrations.AlterField(
            model_name='teammembertranslation',
            name='name',
            field=models.CharField(max_length=100, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='teammembertranslation',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Посада'),
        ),
    ]
