# Generated by Django 5.2 on 2025-06-11 13:24

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('name_uk', models.CharField(max_length=100, null=True, verbose_name="Ім'я")),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name="Ім'я")),
                ('email', models.EmailField(max_length=254, verbose_name='Електронна пошта')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Компанія')),
                ('inquiry_type', models.CharField(choices=[('general', 'Загальне запитання'), ('cooperation', 'Співпраця'), ('complaint', 'Скарга'), ('suggestion', 'Пропозиція'), ('quote', 'Запит вартості')], max_length=50, verbose_name='Тип запиту')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
                ('subject_uk', models.CharField(max_length=200, null=True, verbose_name='Тема')),
                ('subject_en', models.CharField(max_length=200, null=True, verbose_name='Тема')),
                ('message', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Повідомлення')),
                ('message_uk', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Повідомлення')),
                ('message_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Повідомлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Оброблено')),
                ('response', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Відповідь')),
                ('response_uk', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Відповідь')),
                ('response_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Відповідь')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обробки')),
            ],
            options={
                'verbose_name': 'Звернення',
                'verbose_name_plural': 'Звернення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('name_uk', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('address', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Адреса')),
                ('address_uk', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Адреса')),
                ('address_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Адреса')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Опис')),
                ('description_uk', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Опис')),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Опис')),
                ('office_type', models.CharField(choices=[('office', 'Офіс'), ('factory', 'Фабрика'), ('warehouse', 'Склад')], max_length=50, verbose_name='Тип')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Електронна пошта')),
                ('working_hours', models.CharField(blank=True, max_length=200, verbose_name='Години роботи')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Довгота')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_main', models.BooleanField(default=False, verbose_name='Головний офіс')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Офіс/Фабрика',
                'verbose_name_plural': 'Офіси/Фабрики',
                'ordering': ['order'],
            },
        ),
    ]
