# Generated by Django 5.2 on 2025-05-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Електронна пошта'),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Оброблено'),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обробки'),
        ),
        migrations.AlterField(
            model_name='office',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Електронна пошта'),
        ),
        migrations.AlterField(
            model_name='office',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='office',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='office',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Довгота'),
        ),
        migrations.AlterField(
            model_name='office',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='office',
            name='phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='officetranslation',
            name='address',
            field=models.TextField(verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='officetranslation',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='officetranslation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
    ]
