# Generated by Django 5.2 on 2025-05-30 09:20

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contactinquiry_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinquiry',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Повідомлення'),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='response',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Відповідь'),
        ),
        migrations.AlterField(
            model_name='officetranslation',
            name='address',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='officetranslation',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Опис'),
        ),
    ]
