# Generated by Django 5.2.1 on 2025-06-13 13:33

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва вакансії')),
                ('title_uk', models.CharField(max_length=200, null=True, verbose_name='Назва вакансії')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Назва вакансії')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Опис')),
                ('description_uk', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Опис')),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Опис')),
                ('requirements', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Вимоги')),
                ('requirements_uk', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Вимоги')),
                ('requirements_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Вимоги')),
                ('responsibilities', ckeditor_uploader.fields.RichTextUploadingField(verbose_name="Обов'язки")),
                ('responsibilities_uk', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name="Обов'язки")),
                ('responsibilities_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name="Обов'язки")),
                ('benefits', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Переваги')),
                ('benefits_uk', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Переваги')),
                ('benefits_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Переваги')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('employment_type', models.CharField(choices=[('full_time', 'Повна зайнятість'), ('part_time', 'Часткова зайнятість'), ('contract', 'Контракт')], default='full_time', max_length=50, verbose_name='Тип зайнятості')),
                ('experience_required', models.CharField(blank=True, max_length=100, verbose_name='Досвід роботи')),
                ('experience_required_uk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Досвід роботи')),
                ('experience_required_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Досвід роботи')),
                ('salary_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплата від')),
                ('salary_to', models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплата до')),
                ('salary_currency', models.CharField(default='UAH', max_length=10, verbose_name='Валюта')),
                ('location', models.CharField(max_length=200, verbose_name='Місце роботи')),
                ('location_uk', models.CharField(max_length=200, null=True, verbose_name='Місце роботи')),
                ('location_en', models.CharField(max_length=200, null=True, verbose_name='Місце роботи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Терміново')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Термін дії')),
            ],
            options={
                'verbose_name': 'Вакансія',
                'verbose_name_plural': 'Вакансії',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkplacePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва')),
                ('title_uk', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('description_uk', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('image', models.ImageField(upload_to='workplace/', verbose_name='Зображення')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Фото робочого місця',
                'verbose_name_plural': 'Фото робочих місць',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('email', models.EmailField(max_length=254, verbose_name='Електронна пошта')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Супровідний лист')),
                ('resume', models.FileField(upload_to='resumes/', verbose_name='Резюме')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='Переглянуто')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobposition', verbose_name='Вакансія')),
            ],
            options={
                'verbose_name': 'Заявка на вакансію',
                'verbose_name_plural': 'Заявки на вакансії',
                'ordering': ['-created_at'],
            },
        ),
    ]
