# Generated by Django 5.2 on 2025-05-30 07:30

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Електронна пошта'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='is_reviewed',
            field=models.BooleanField(default=False, verbose_name='Переглянуто'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobposition', verbose_name='Вакансія'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Повна зайнятість'), ('part_time', 'Часткова зайнятість'), ('contract', 'Контракт')], default='full_time', max_length=50, verbose_name='Тип зайнятості'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Термін дії'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='salary_currency',
            field=models.CharField(default='UAH', max_length=10, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='salary_from',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплата від'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='salary_to',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплата до'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='jobpositiontranslation',
            name='benefits',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Переваги'),
        ),
        migrations.AlterField(
            model_name='jobpositiontranslation',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='jobpositiontranslation',
            name='requirements',
            field=ckeditor.fields.RichTextField(verbose_name='Вимоги'),
        ),
        migrations.AlterField(
            model_name='jobpositiontranslation',
            name='responsibilities',
            field=ckeditor.fields.RichTextField(verbose_name="Обов'язки"),
        ),
        migrations.AlterField(
            model_name='jobpositiontranslation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Назва вакансії'),
        ),
        migrations.AlterField(
            model_name='workplacephoto',
            name='image',
            field=models.ImageField(upload_to='workplace/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='workplacephoto',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='workplacephoto',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='workplacephototranslation',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='workplacephototranslation',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
    ]
