# Generated by Django 5.2 on 2025-05-28 12:49

import ckeditor.fields
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Назва компанії')),
                ('contact_person', models.CharField(max_length=100, verbose_name='Контактна особа')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('inquiry_type', models.CharField(choices=[('cooperation', 'Співпраця'), ('quote', 'Запит на розрахунок'), ('samples', 'Зразки продукції'), ('other', 'Інше')], max_length=50, verbose_name='Тип запиту')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('project_description', models.TextField(blank=True, verbose_name='Опис проєкту')),
                ('estimated_quantity', models.CharField(blank=True, max_length=100, verbose_name='Орієнтовна кількість')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Запит партнера',
                'verbose_name_plural': 'Запити партнерів',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnershipInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_order_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Мін. сума замовлення')),
                ('production_capacity', models.CharField(blank=True, max_length=200, verbose_name='Виробнича потужність')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Інформація для партнерів',
                'verbose_name_plural': 'Інформація для партнерів',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WorkStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('duration', models.CharField(blank=True, max_length=50, verbose_name='Тривалість')),
            ],
            options={
                'verbose_name': 'Етап роботи',
                'verbose_name_plural': 'Етапи роботи',
                'ordering': ['order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PartnershipInfoTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('cooperation_terms', ckeditor.fields.RichTextField(verbose_name='Умови співпраці')),
                ('work_stages', ckeditor.fields.RichTextField(verbose_name='Етапи роботи')),
                ('faq_content', ckeditor.fields.RichTextField(verbose_name='FAQ для замовників')),
                ('benefits', ckeditor.fields.RichTextField(blank=True, verbose_name='Переваги співпраці')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='partners.partnershipinfo')),
            ],
            options={
                'verbose_name': 'Інформація для партнерів Translation',
                'db_table': 'partners_partnershipinfo_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WorkStageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='partners.workstage')),
            ],
            options={
                'verbose_name': 'Етап роботи Translation',
                'db_table': 'partners_workstage_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
