# Generated by Django 5.2.1 on 2025-06-13 13:33

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Назва компанії')),
                ('contact_person', models.CharField(max_length=100, verbose_name='Контактна особа')),
                ('email', models.EmailField(max_length=254, verbose_name='Електронна пошта')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('inquiry_type', models.CharField(choices=[('cooperation', 'Співпраця'), ('quote', 'Запит на розрахунок'), ('samples', 'Зразки продукції'), ('other', 'Інше')], max_length=50, verbose_name='Тип запиту')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('project_description', models.TextField(blank=True, verbose_name='Опис проєкту')),
                ('estimated_quantity', models.CharField(blank=True, max_length=100, verbose_name='Орієнтовна кількість')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Оброблено')),
            ],
            options={
                'verbose_name': 'Запит партнера',
                'verbose_name_plural': 'Запити партнерів',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnershipInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperation_terms', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Умови співпраці')),
                ('cooperation_terms_uk', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Умови співпраці')),
                ('cooperation_terms_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Умови співпраці')),
                ('work_stages', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Етапи роботи')),
                ('work_stages_uk', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Етапи роботи')),
                ('work_stages_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Етапи роботи')),
                ('faq_content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='FAQ для замовників')),
                ('faq_content_uk', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='FAQ для замовників')),
                ('faq_content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='FAQ для замовників')),
                ('benefits', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Переваги співпраці')),
                ('benefits_uk', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Переваги співпраці')),
                ('benefits_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Переваги співпраці')),
                ('min_order_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Мін. сума замовлення')),
                ('production_capacity', models.CharField(blank=True, max_length=200, verbose_name='Виробнича потужність')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('work_stages_info', models.TextField()),
            ],
            options={
                'verbose_name': 'Інформація для партнерів',
                'verbose_name_plural': 'Інформація для партнерів',
            },
        ),
        migrations.CreateModel(
            name='WorkStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва')),
                ('title_uk', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('description_uk', models.TextField(null=True, verbose_name='Опис')),
                ('description_en', models.TextField(null=True, verbose_name='Опис')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Іконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('duration', models.CharField(blank=True, max_length=50, verbose_name='Тривалість')),
            ],
            options={
                'verbose_name': 'Етап роботи',
                'verbose_name_plural': 'Етапи роботи',
                'ordering': ['order'],
            },
        ),
    ]
