# Generated by Django 5.2 on 2025-05-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerinquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='partnerinquiry',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Електронна пошта'),
        ),
        migrations.AlterField(
            model_name='partnerinquiry',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Оброблено'),
        ),
        migrations.AlterField(
            model_name='partnerinquiry',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='partnershipinfo',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='partnershipinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='workstage',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Іконка'),
        ),
        migrations.AlterField(
            model_name='workstage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='workstagetranslation',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='workstagetranslation',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
    ]
