# Generated by Django 5.2 on 2025-06-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partnerinquiry_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnershipinfo',
            name='work_stages_info',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
